---
- name: reload facts
  action: setup

### yum ###
- name: yum clean all
  become: yes
  command: yum clean all

- name: yum repolist
  become: yes
  command: yum repolist
  ignore_errors: yes

- name: yum upgrade
  become: yes
  yum: name=* state=latest
