version: '2'

volumes:
  beaker-db-data:

services:
  sandbox:
    build: ./dev
    image: beaker-dev
    working_dir: /home/dev
    privileged: true
    volumes:
      - ../../beaker:/home/dev/beaker
      - ./:/opt/entrypoints
    ports:
      - "8080:8080"
    entrypoint:
      - /opt/entrypoints/runwithlocaluser.sh

  beaker-database:
    build: ./db
    image: beaker-db
    volumes:
      - beaker-db-data:/var/lib/mysql
    expose:
      - 3306
