---
- name: clone the beaker repository
  git:
    repo: https://github.com/beaker-project/beaker.git
    depth: 1
    dest: /tmp/beaker
    version: develop
    accept_hostkey: yes

- name: install yum utility
  become: yes
  yum:
    name: yum-utils
    state: present

- name: install dependent beaker packages
  become: yes
  command: "yum-builddep -y /tmp/beaker/beaker.spec"

- name: remove temporary cloned beaker repository
  command: "rm -rf /tmp/beaker"

- name: install runtime dependencies
  become: yes
  yum:
    name:
        - firefox
        - nodejs-less
        - openldap-servers
        - python-gunicorn
        - python-isodate
        - python-kerberos
        - python-lockfile
        - python-nose-progressive
        - python-rdflib
        - python-requests-kerberos
        - python-tgexpandingformwidget
        - selenium-python
        - uglify-js
        - xorg-x11-server-Xvfb
        - pylint
        - pytest
        - xz  # to import database dumps
        - centos-release-openstack-stein  # OpenStack
    state: present
    enablerepo: "beaker-server-testing"

- name: install OpenStack deps
  become: yes
  yum:
    name:
        - python-keystoneclient
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
    state: present

- name: workaround | delete installed TG version
  become: yes
  yum:
    name: "TurboGears"
    state: absent

- name: workaround | prefer custom build TG from beaker server
  become: yes
  yum:
    name: "TurboGears-1.1.3-8.el7.noarch"
    state: present
