---
- hosts: all
  roles:
    - { role: setup/validate-host, tags: base-system }
    - { role: setup/base-system, tags: base-system }

- hosts: all
  roles:
    - { role: beaker/setup/repos, tags: beaker }
    - { role: beaker/setup/packages, tags: beaker }
  tasks:
    - debug: msg="Setup successfull, Enjoy!"
