---
- name: Run init
  command: python bkr/server/tools/init.py --user={{ user }} --password={{ password }} --email={{ email }}
  args:
    chdir: "/home/dev/beaker/Server"
  environment:
    PYTHONPATH: "../Common:."
