name: Docker Compose CI

on:
  push:
    branches:
      - master  # Push events on master branch
  pull_request:
    branches:
      - '**'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
